### ISSUE TITLE
Bankrupting a tab containing "<iframe>" in title breaks tab-bankrupter

### ISSUE THREAD

**Issue by zencephalon** [jsvine/tab-bankrupter#3]
ILUVU @jsvine,

Don't know if U remember me but we met for coffee once to discuss version controlled writing. Anyway, I've used tab-bankrupter for years at this point and it has proven super solid and bullet proof. I love using software that just works and doesn't update.

I did finally find a bug in it though. When I bankrupted [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) things got funky.

Might want to export before trying to reproduce this.

![screen shot 2016-06-16 at 3 52 14 pm](https://cloud.githubusercontent.com/assets/1297679/16131098/584f0e0e-33da-11e6-95e3-5316284ae5f1.png)

**Comment by jsvine** [comment]
Hey, hey! Nice to hear from you, and great bug-find. Looks like I need to `escape(...)` the titles.

**Comment by jsvine** [comment]
Thanks again! Should be fixed now. Let me know if not.
